-
Koolana/AdvCpp pull request #3
Opened 2020-03-20 09:44 UTC by Koolana

2020-03-20 13:32 UTC, smirnov-vs requested changes
Есть серьезные архитектурные проблемы с которыми надо разобраться.
И есть по мелочи синтаксические проблемы, которые тоже важно проработать, чтобы писать современно

2020-03-20 13:32 UTC, smirnov-vs commented on include/process.h
> +    char buf;
какое-то лишнее поле осталось

2020-03-20 13:32 UTC, smirnov-vs commented on include/process.h
> +    int pipefdOut[2];
классу достаточно знать 2 дескриптора

2020-03-20 13:32 UTC, smirnov-vs commented on main.cpp
> +        oneProc.readExact((void*)tempStr, 14); //"зависнет" пока не считает все 14 байт
к void* кастить не надо

2020-03-20 13:32 UTC, smirnov-vs commented on main.cpp
> +    char* tempStr = new char[255];
тут ошибка

2020-03-20 13:32 UTC, smirnov-vs commented on main.cpp
> +    char* tempStr = new char[255];
и зачем такой маленький буфер в кучу?

2020-03-20 13:32 UTC, smirnov-vs commented on mainProc.cpp
> +        exit(EXIT_FAILURE);
почему используем exit?

2020-03-20 13:32 UTC, smirnov-vs commented on mainProc.cpp
> +        perror("pipes"); //нет нужного кол-ва аргументов
perror никто не использует, пишем на C++

2020-03-20 13:32 UTC, smirnov-vs commented on src/process.cpp
> +        //передаем концы пайп как аргументы в дочерний процесс
это неверная тактика, дочерний процесс вообще не знает, что ему там подменяют что-то

2020-03-20 13:32 UTC, smirnov-vs commented on src/process.cpp
> +        throw "Error open Pipe write";
примитивные типы не бросают, тогда от исключений нет смысла

2020-03-20 13:32 UTC, smirnov-vs commented on src/process.cpp
> +        perror("pipeIn");
библиотеки не общаются с консолью

2020-03-20 13:32 UTC, smirnov-vs commented on src/process.cpp
> +    size_t numByte = ::write(pipefdIn[1], data, len);
`write` возвращает не size_t

2020-03-20 13:32 UTC, smirnov-vs commented on src/process.cpp
> +        if (tempS < 0) {
это всегда `false`

2020-03-20 13:32 UTC, smirnov-vs commented on src/process.cpp
> +            ((char*)data)[s + i] = tempData[i];
зачем лишнее копирование? буфер уже предоставлен, можно сразу туда

2020-03-20 13:32 UTC, smirnov-vs commented on src/process.cpp
> +    return !::read(pipefdOut[0], NULL, 0);
зависнуть может

2020-03-20 13:32 UTC, smirnov-vs commented on src/process.cpp
> +void Process::close()
этот метод закрывает процесс

2020-03-23 20:55 UTC, smirnov-vs requested changes

2020-03-23 20:55 UTC, smirnov-vs commented on src/process.cpp
> +void Process::writeExact(const void* data, size_t len)
этот метод работает неправильно

2020-03-23 20:55 UTC, smirnov-vs commented on src/process.cpp
> +        throw std::exception();
первый пайп утек у тебя

2020-03-23 20:55 UTC, smirnov-vs commented on src/process.cpp
> +        throw std::exception();
в исключении нет сообщения никакого, как понять потом где у тебя проблемесы?

2020-03-23 20:55 UTC, smirnov-vs commented on src/process.cpp
> +    isReadableFlag = false;
это вход к тебе от процесса, он сам решает когда ему закрыть его stdout
это архитектурно неверно закрывать чужую сторону

2020-03-23 20:55 UTC, smirnov-vs commented on src/process.cpp
> +    waitpid(cpid, NULL, 0);
забыл закрыть пайпы

2020-03-24 22:45 UTC, smirnov-vs commented on src/process.cpp
> +            throw std::runtime_error("Error execl() in child");
теперь тут утечки, везде писать придется?)

2020-03-25 21:32 UTC, smirnov-vs approved these changes
окей, кому баллы ставим?

2020-03-25 22:20 UTC, Koolana commented
> 
> 
> окей, кому баллы ставим?

Мне конечно же). Я просто пересмотрел 2 лекцию, а именно про часть с RAII, и там меня заинтересовал пример с Pipe, как отдельный класс, вот и решил его попробовать реализовать. Мне показалось это оптимальным решением, переложить всю ответственность по захвату и освобождению ресурса на конструктор и деструктор соответственно, чтобы не отлавливать утечки пайпы по всему коду.

2020-03-25 22:22 UTC, smirnov-vs commented
Это все верно и хорошо, я просто не могу нигде найти имя фамилию

2020-03-25 22:27 UTC, Koolana commented
> 
> 
> Это все верно и хорошо, я просто не могу нигде найти имя фамилию

это Николай Андрейчик

2020-03-28 12:15 UTC, merged